name: anti
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  geolocator: ^12.0.0
  image_picker: ^1.1.1
  firebase_storage: ^11.7.7
  intl: ^0.19.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/logos.png
    - assets/images/notif.png
    - assets/images/ponsel.png
    - assets/images/lokasi.png
    - assets/images/person.png
    - assets/images/donasimasuk.png
    - assets/images/penerimadonasi.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
