// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYgvEOz6ooVECYAeC6cuPiAs8QkjWrn3w',
    appId: '1:207956747286:web:87bcc42899008b65298137',
    messagingSenderId: '207956747286',
    projectId: 'antimubazir-474ad',
    authDomain: 'antimubazir-474ad.firebaseapp.com',
    storageBucket: 'antimubazir-474ad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBplPge7MJjsZn7JOv3n5vrF8dDUTM-Bl0',
    appId: '1:207956747286:android:dc147c2c587b4f91298137',
    messagingSenderId: '207956747286',
    projectId: 'antimubazir-474ad',
    storageBucket: 'antimubazir-474ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqQc8V4qxeER6DXvgnq2BR1gK1mBwUyr4',
    appId: '1:207956747286:ios:2a64a3ebe230f99d298137',
    messagingSenderId: '207956747286',
    projectId: 'antimubazir-474ad',
    storageBucket: 'antimubazir-474ad.appspot.com',
    iosBundleId: 'com.example.antimubazir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqQc8V4qxeER6DXvgnq2BR1gK1mBwUyr4',
    appId: '1:207956747286:ios:2a64a3ebe230f99d298137',
    messagingSenderId: '207956747286',
    projectId: 'antimubazir-474ad',
    storageBucket: 'antimubazir-474ad.appspot.com',
    iosBundleId: 'com.example.antimubazir',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYgvEOz6ooVECYAeC6cuPiAs8QkjWrn3w',
    appId: '1:207956747286:web:f166b32b7ebd64a2298137',
    messagingSenderId: '207956747286',
    projectId: 'antimubazir-474ad',
    authDomain: 'antimubazir-474ad.firebaseapp.com',
    storageBucket: 'antimubazir-474ad.appspot.com',
  );
}
